//reducer actions
export const R_START_LOAD_MULTIPLAYER_GAMES = 'R_START_LOAD_MULTIPLAYER_GAMES';
export const R_FINISH_LOAD_MULTIPLAYER_GAMES = 'R_FINISH_LOAD_MULTIPLAYER_GAMES';
export const R_START_USER_ADD = 'R_START_USER_ADD';
export const R_FINISH_USER_ADD = 'R_FINISH_USER_ADD';
export const R_USER_DELETE = 'R_USER_DELETE';
export const R_DO_INTERSECTION = 'R_DO_INTERSECTION';
export const R_SHOW_ERROR = 'R_SHOW_ERROR';
export const R_HIDE_ERROR = 'R_HIDE_ERROR';

//sagas actions
export const S_LOAD_MULTIPLAYER_GAMES = 'S_LOAD_MULTIPLAYER_GAMES';
export const S_USER_ADD = 'S_USER_ADD';
export const S_USER_DELETE = 'S_USER_DELETE';
